on:
  push:

jobs:
  build-gradle-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Build App'
      id: build
      run: |
        gradle build
        echo 'result=SUCCESS' >> $GITHUB_OUTPUT

    - name: 'Run Tests'
      if: ${{ steps.build.outputs.result == 'SUCCESS' }}
      run: gradle test

    - name: 'Create JAR-artifact'
      run: |
        gradle jar
        echo "Deploy jar to gcr"
        ls
        find . -name "*.jar"



    


